[package]
name = "dashmap"
version = "2.0.0"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.nebulanet.cc/xacrimon/dashmap"
homepage = "https://gitlab.nebulanet.cc/xacrimon/dashmap"
description = "Extremely fast concurrent map."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[features]
nightly = ["parking_lot/nightly", "dashmap-shard/nightly"]

[dev-dependencies]
criterion = "0.3"
rayon = "1.2.0"

[[bench]]
name = "rwlock_std"
harness = false

[[bench]]
name = "dashmap"
harness = false

[dependencies]
dashmap-shard = { version = "0.1.1", default-features = false }
parking_lot = "0.9.0"
num_cpus = "1.11.1"
fxhash = "0.2.1"
