[package]
name = "dashmap"
version = "1.2.1"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.nebulanet.cc/xacrimon/dashmap"
homepage = "https://gitlab.nebulanet.cc/xacrimon/dashmap"
description = "Extremely fast concurrent map."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[features]
nightly = ["parking_lot/nightly", "dashmap-shard/nightly"]

[dependencies]
dashmap-shard = "0.1.0"
parking_lot = "0.9.0"
num_cpus = "1.10.1"
fxhash = "0.2.1"
