[package]
name = "dashmap"
version = "3.8.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/dashmap"
homepage = "https://github.com/xacrimon/dashmap"
description = "Blazing fast concurrent HashMap for Rust."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[features]
default = []
raw-api = []
no_std = ["hashbrown"]

[dev-dependencies]
criterion = "0.3.0"
rayon = "1.2.1"
chashmap = "2.2.2"
contrie = "0.1.4"
cht = "0.1.2"
fxhash = "0.2.1"

[[bench]]
name = "rwlock_std"
harness = false

[[bench]]
name = "dashmap"
harness = false

[[bench]]
name = "chashmap"
harness = false

[[bench]]
name = "contrie"
harness = false

[dependencies]
num_cpus = "1.11.1"
ahash = "0.3.1"
serde = { version = "1.0.104", optional = true, features = ["derive"] }
cfg-if = "0.1.10"
hashbrown = { version = "0.7.1", optional = true }

[package.metadata.docs.rs]
all-features = true
