name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests with features
      run: cargo test --verbose --features raw-api serde
